- name: required packages installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
    update_cache: true
  become: true

- name: signing key added
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  become: true

- name: docker repository in sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true

- name: docker installed
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-compose
    state: latest
    update_cache: true
  become: true

       