- name: files copied to vault server
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0440"
  with_items:
    - src: ./nomad-server-policy.hcl
      dest: "{{ nomad_server_policy_dest }}"
    - src: ./nomad-cluster-role.json
      dest: "{{ nomad_cluster_role_dest }}"
  become: true

- name: nomad-server policy is set
  ansible.builtin.command: vault policy write nomad-server "{{ nomad_server_policy_dest }}"
  register: vault_policy_write
  become: true

- name: nomad-cluster role is set
  ansible.builtin.command: vault write auth/token/roles/nomad-cluster @"{{ nomad_cluster_role_dest }}"
  register: vault_role_write
  become: true

- name: token is created
  ansible.builtin.command: vault token create -policy=nomad-server -period=72h -orphan -format=yml
  register: vault_token_create
  become: true

- name: vault token saved
  ansible.builtin.set_fact: hashi_vault_token="{{ vault_token_create.stdout | from_yaml | json_query('auth.client_token') }}"

