- name: profile contains vault address
  lineinfile:
    dest: ~/.profile
    state: present
    line: "VAULT_ADDR={{ hashi_vault_api_address }}"

- name: source profile
  ansible.builtin.shell: source ~/.profile

- name: check status of vault
  ansible.builtin.command: vault status -format=yaml
  register: vault_status_raw
  failed_when: vault_status_raw.rc is not in [0, 1, 2]

- name: vault_status saved
  ansible.builtin.set_fact:
    vault_status: "{{ vault_status_raw.stdout | from_yaml }}"

- name: vault initialized 
  ansible.builtin.command:
    cmd: vault operator init -key-shares=1 -key-threshold=1 -format=yaml
  register: vault_operator_init
  when:
    - not vault_status.initialized

- name: vault_init_output is saved
  ansible.builtin.set_fact:
    vault_init_output: "{{ vault_operator_init.stdout | from_yaml }}"
  when:
    - vault_operator_init is defined
    - vault_operator_init.stdout is defined

- name: vault unsealed
  block:
    - name: Show unseal information
      block:
        - name: Show unseal keys for leader
          ansible.builtin.debug:
            msg: "{{ vault_init_output.unseal_keys_b64 }}"

        - name: Show root token for leader
          ansible.builtin.debug:
            msg: "{{ vault_init_output.root_token }}"
          when:
            - vault_init_output is defined and
              vault_init_output.root_token is defined
      - name: Unseal vault
        ansible.builtin.command:
          cmd: vault operator unseal {{ item }}
        loop: "{{ vault_init_output.unseal_keys_b64 }}"
        loop_control:
          label: "hidden"
        no_log: yes
        when:
          - vault_status.sealed
  when:
    - vault_init_output is defined and
      vault_init_output.unseal_keys_b64 is defined and
      vault_init_output.unseal_keys_b64 is iterable

- name: profile contains vault token
  lineinfile:
    dest: ~/.profile
    state: present
    line: "VAULT_TOKEN={{ cault_init_output.root_token }}"

- name: source profile
  ansible.builtin.shell: source ~/.profile

- name: check if vault is initialized
  ansible.builtin.assert:
    that:
      - vault_status.initialized | bool
    quiet: yes

- name: check if vault is unsealed
  ansible.builtin.assert:
    that:
      - not vault_status.sealed | bool
    quiet: yes
