- name: vault installed
  ansible.builtin.apt:
    name:
      - vault
    state: latest
    update_cache: true
  become: true

- name: vault config
  template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    mode: "0440"
  notify:
    - restart vault
  become: true

- name: vault agent service
  systemd:
    name: vault
    state: started
    daemon_reload: yes
    enabled: true
  vars:
    ansible_command_timeout: 30
  become: true

- name: vault initialized and unsealed
  import_tasks: init.yml
  tags: vault-init
  environment:
    VAULT_ADDR: "{{ hashi_vault_api_address }}"
    
- name: vault configured
  import_tasks: configure.yml
  tags: vault-configure
  environment:
    VAULT_ADDR: "{{ hashi_vault_api_address }}"
    VAULT_TOKEN: "{{ vault_init_output.root_token }}"

